[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
    'npm run install-server',
    'npm run install-client'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'cd server && npm start' 